#############################################################################
# Makefile for building: Simulation
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  Simulation.pro
# Template: app
# Command: /home/gaultier/Qt/5.3/gcc_64/bin/qmake -spec linux-clang CONFIG+=debug -o Makefile Simulation.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = 
CFLAGS        = -pipe -g -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -Ofast -Wno-deprecated -g -std=c++11 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../Qt/5.3/gcc_64/mkspecs/linux-clang -I.
LINK          = clang++
LFLAGS        = -ccc-gcc-name g++ -Ofast -Wl,-rpath,/home/gaultier/Qt/5.3/gcc_64
LIBS          = $(SUBLIBS) -lSDL2 -lGL -lGLU -lSDL2_image -lGLEW -lovr -lpthread -lX11 -ludev -lXinerama -lXrandr 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/gaultier/Qt/5.3/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Camera.cpp \
		Crate.cpp \
		Cube.cpp \
		GraphicObject.cpp \
		Input.cpp \
		Log.cpp \
		main.cpp \
		Oculus.cpp \
		Plane.cpp \
		Scene.cpp \
		Shader.cpp \
		Texture.cpp \
		Utils.cpp 
OBJECTS       = Camera.o \
		Crate.o \
		Cube.o \
		GraphicObject.o \
		Input.o \
		Log.o \
		main.o \
		Oculus.o \
		Plane.o \
		Scene.o \
		Shader.o \
		Texture.o \
		Utils.o
DIST          = ../Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../Qt/5.3/gcc_64/mkspecs/common/unix.conf \
		../Qt/5.3/gcc_64/mkspecs/common/linux.conf \
		../Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Qt/5.3/gcc_64/mkspecs/common/clang.conf \
		../Qt/5.3/gcc_64/mkspecs/qconfig.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../Qt/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../Qt/5.3/gcc_64/mkspecs/linux-clang/qmake.conf \
		../Qt/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../Qt/5.3/gcc_64/mkspecs/features/default_post.prf \
		../Qt/5.3/gcc_64/mkspecs/features/c++11.prf \
		../Qt/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../Qt/5.3/gcc_64/mkspecs/features/yacc.prf \
		../Qt/5.3/gcc_64/mkspecs/features/lex.prf \
		Simulation.pro Camera.cpp \
		Crate.cpp \
		Cube.cpp \
		GraphicObject.cpp \
		Input.cpp \
		Log.cpp \
		main.cpp \
		Oculus.cpp \
		Plane.cpp \
		Scene.cpp \
		Shader.cpp \
		Texture.cpp \
		Utils.cpp
QMAKE_TARGET  = Simulation
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Simulation


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Simulation.pro ../Qt/5.3/gcc_64/mkspecs/linux-clang/qmake.conf ../Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../Qt/5.3/gcc_64/mkspecs/common/unix.conf \
		../Qt/5.3/gcc_64/mkspecs/common/linux.conf \
		../Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Qt/5.3/gcc_64/mkspecs/common/clang.conf \
		../Qt/5.3/gcc_64/mkspecs/qconfig.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../Qt/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../Qt/5.3/gcc_64/mkspecs/linux-clang/qmake.conf \
		../Qt/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../Qt/5.3/gcc_64/mkspecs/features/default_post.prf \
		../Qt/5.3/gcc_64/mkspecs/features/c++11.prf \
		../Qt/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../Qt/5.3/gcc_64/mkspecs/features/yacc.prf \
		../Qt/5.3/gcc_64/mkspecs/features/lex.prf \
		Simulation.pro
	$(QMAKE) -spec linux-clang CONFIG+=debug -o Makefile Simulation.pro
../Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf:
../Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf:
../Qt/5.3/gcc_64/mkspecs/common/unix.conf:
../Qt/5.3/gcc_64/mkspecs/common/linux.conf:
../Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf:
../Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
../Qt/5.3/gcc_64/mkspecs/common/clang.conf:
../Qt/5.3/gcc_64/mkspecs/qconfig.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf:
../Qt/5.3/gcc_64/mkspecs/features/qt_config.prf:
../Qt/5.3/gcc_64/mkspecs/linux-clang/qmake.conf:
../Qt/5.3/gcc_64/mkspecs/features/spec_post.prf:
../Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf:
../Qt/5.3/gcc_64/mkspecs/features/default_pre.prf:
../Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf:
../Qt/5.3/gcc_64/mkspecs/features/default_post.prf:
../Qt/5.3/gcc_64/mkspecs/features/c++11.prf:
../Qt/5.3/gcc_64/mkspecs/features/warn_on.prf:
../Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf:
../Qt/5.3/gcc_64/mkspecs/features/exceptions.prf:
../Qt/5.3/gcc_64/mkspecs/features/yacc.prf:
../Qt/5.3/gcc_64/mkspecs/features/lex.prf:
Simulation.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-clang CONFIG+=debug -o Makefile Simulation.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/Simulation1.0.0 || mkdir -p .tmp/Simulation1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/Simulation1.0.0/ && (cd `dirname .tmp/Simulation1.0.0` && $(TAR) Simulation1.0.0.tar Simulation1.0.0 && $(COMPRESS) Simulation1.0.0.tar) && $(MOVE) `dirname .tmp/Simulation1.0.0`/Simulation1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Simulation1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

Camera.o: Camera.cpp Camera.h \
		Include/glm/glm.hpp \
		Include/glm/core/_fixes.hpp \
		Include/glm/core/setup.hpp \
		Include/glm/core/_detail.hpp \
		Include/glm/core/_vectorize.hpp \
		Include/glm/core/type.hpp \
		Include/glm/core/type_half.hpp \
		Include/glm/core/type_half.inl \
		Include/glm/core/type_float.hpp \
		Include/glm/core/type_int.hpp \
		Include/glm/core/type_gentype.hpp \
		Include/glm/core/type_size.hpp \
		Include/glm/core/type_vec1.hpp \
		Include/glm/core/type_vec.hpp \
		Include/glm/core/_swizzle.hpp \
		Include/glm/core/_swizzle_func.hpp \
		Include/glm/core/type_vec1.inl \
		Include/glm/core/type_vec2.hpp \
		Include/glm/core/type_vec2.inl \
		Include/glm/core/type_vec3.hpp \
		Include/glm/core/type_vec3.inl \
		Include/glm/core/type_vec4.hpp \
		Include/glm/core/type_vec4.inl \
		Include/glm/core/type_mat2x2.hpp \
		Include/glm/core/type_mat.hpp \
		Include/glm/core/type_mat2x2.inl \
		Include/glm/core/type_mat2x3.hpp \
		Include/glm/core/type_mat2x3.inl \
		Include/glm/core/type_mat2x4.hpp \
		Include/glm/core/type_mat2x4.inl \
		Include/glm/core/type_mat3x2.hpp \
		Include/glm/core/type_mat3x2.inl \
		Include/glm/core/type_mat3x3.hpp \
		Include/glm/core/type_mat3x3.inl \
		Include/glm/core/type_mat3x4.hpp \
		Include/glm/core/type_mat3x4.inl \
		Include/glm/core/type_mat4x2.hpp \
		Include/glm/core/type_mat4x2.inl \
		Include/glm/core/type_mat4x3.hpp \
		Include/glm/core/type_mat4x3.inl \
		Include/glm/core/type_mat4x4.hpp \
		Include/glm/core/type_mat4x4.inl \
		Include/glm/core/func_trigonometric.hpp \
		Include/glm/core/func_trigonometric.inl \
		Include/glm/core/func_exponential.hpp \
		Include/glm/core/func_exponential.inl \
		Include/glm/core/func_common.hpp \
		Include/glm/core/func_common.inl \
		Include/glm/core/func_packing.hpp \
		Include/glm/core/func_packing.inl \
		Include/glm/core/func_geometric.hpp \
		Include/glm/core/func_geometric.inl \
		Include/glm/core/func_matrix.hpp \
		Include/glm/core/func_matrix.inl \
		Include/glm/core/func_vector_relational.hpp \
		Include/glm/core/func_vector_relational.inl \
		Include/glm/core/func_integer.hpp \
		Include/glm/core/func_integer.inl \
		Include/glm/core/func_noise.hpp \
		Include/glm/core/func_noise.inl \
		Input.h \
		Oculus.h \
		Include/OVR/LibOVR/Include/OVR.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Allocator.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Types.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Log.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Math.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_RefCount.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Std.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Alg.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_System.h \
		Include/OVR/LibOVR/Src/OVR_Device.h \
		Include/OVR/LibOVR/Src/OVR_DeviceConstants.h \
		Include/OVR/LibOVR/Src/OVR_DeviceHandle.h \
		Include/OVR/LibOVR/Src/OVR_DeviceMessages.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Array.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_ContainerAllocator.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Color.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_String.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_UTF8Util.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Atomic.h \
		Include/OVR/LibOVR/Src/OVR_HIDDeviceBase.h \
		Include/OVR/LibOVR/Src/OVR_SensorFusion.h \
		Include/OVR/LibOVR/Src/OVR_SensorFilter.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Deque.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Timer.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Threads.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Lockless.h \
		Include/OVR/LibOVR/Src/OVR_Stereo.h \
		Include/OVR/LibOVR/Src/OVR_Profile.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_StringHash.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Hash.h \
		Include/OVR/LibOVR/Src/Util/Util_LatencyTest.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_List.h \
		Include/OVR/LibOVR/Src/Util/Util_Render_Stereo.h \
		Include/OVR/LibOVR/Src/Util/Util_Interface.h \
		Include/OVR/LibOVR/Src/OVR_CAPI.h \
		Include/OVR/LibOVR/Src/OVR_CAPI_GL.h \
		Include/GL3/gl3.h \
		Utils.h \
		Log.h \
		Include/glm/gtx/transform.hpp \
		Include/glm/gtc/matrix_transform.hpp \
		Include/glm/gtc/matrix_transform.inl \
		Include/glm/gtx/transform.inl \
		Include/glm/gtc/type_ptr.hpp \
		Include/glm/gtc/half_float.hpp \
		Include/glm/gtc/half_float.inl \
		Include/glm/gtc/quaternion.hpp \
		Include/glm/gtc/constants.hpp \
		Include/glm/gtc/constants.inl \
		Include/glm/gtc/quaternion.inl \
		Include/glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Camera.o Camera.cpp

Crate.o: Crate.cpp Utils.h \
		Include/glm/glm.hpp \
		Include/glm/core/_fixes.hpp \
		Include/glm/core/setup.hpp \
		Include/glm/core/_detail.hpp \
		Include/glm/core/_vectorize.hpp \
		Include/glm/core/type.hpp \
		Include/glm/core/type_half.hpp \
		Include/glm/core/type_half.inl \
		Include/glm/core/type_float.hpp \
		Include/glm/core/type_int.hpp \
		Include/glm/core/type_gentype.hpp \
		Include/glm/core/type_size.hpp \
		Include/glm/core/type_vec1.hpp \
		Include/glm/core/type_vec.hpp \
		Include/glm/core/_swizzle.hpp \
		Include/glm/core/_swizzle_func.hpp \
		Include/glm/core/type_vec1.inl \
		Include/glm/core/type_vec2.hpp \
		Include/glm/core/type_vec2.inl \
		Include/glm/core/type_vec3.hpp \
		Include/glm/core/type_vec3.inl \
		Include/glm/core/type_vec4.hpp \
		Include/glm/core/type_vec4.inl \
		Include/glm/core/type_mat2x2.hpp \
		Include/glm/core/type_mat.hpp \
		Include/glm/core/type_mat2x2.inl \
		Include/glm/core/type_mat2x3.hpp \
		Include/glm/core/type_mat2x3.inl \
		Include/glm/core/type_mat2x4.hpp \
		Include/glm/core/type_mat2x4.inl \
		Include/glm/core/type_mat3x2.hpp \
		Include/glm/core/type_mat3x2.inl \
		Include/glm/core/type_mat3x3.hpp \
		Include/glm/core/type_mat3x3.inl \
		Include/glm/core/type_mat3x4.hpp \
		Include/glm/core/type_mat3x4.inl \
		Include/glm/core/type_mat4x2.hpp \
		Include/glm/core/type_mat4x2.inl \
		Include/glm/core/type_mat4x3.hpp \
		Include/glm/core/type_mat4x3.inl \
		Include/glm/core/type_mat4x4.hpp \
		Include/glm/core/type_mat4x4.inl \
		Include/glm/core/func_trigonometric.hpp \
		Include/glm/core/func_trigonometric.inl \
		Include/glm/core/func_exponential.hpp \
		Include/glm/core/func_exponential.inl \
		Include/glm/core/func_common.hpp \
		Include/glm/core/func_common.inl \
		Include/glm/core/func_packing.hpp \
		Include/glm/core/func_packing.inl \
		Include/glm/core/func_geometric.hpp \
		Include/glm/core/func_geometric.inl \
		Include/glm/core/func_matrix.hpp \
		Include/glm/core/func_matrix.inl \
		Include/glm/core/func_vector_relational.hpp \
		Include/glm/core/func_vector_relational.inl \
		Include/glm/core/func_integer.hpp \
		Include/glm/core/func_integer.inl \
		Include/glm/core/func_noise.hpp \
		Include/glm/core/func_noise.inl \
		Include/OVR/LibOVR/Src/Kernel/OVR_Math.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Types.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_RefCount.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Allocator.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Std.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Alg.h \
		Crate.h \
		Cube.h \
		GraphicObject.h \
		Shader.h \
		Include/GL3/gl3.h \
		Texture.h \
		Include/glm/gtx/transform.hpp \
		Include/glm/gtc/matrix_transform.hpp \
		Include/glm/gtc/matrix_transform.inl \
		Include/glm/gtx/transform.inl \
		Include/glm/gtc/type_ptr.hpp \
		Include/glm/gtc/half_float.hpp \
		Include/glm/gtc/half_float.inl \
		Include/glm/gtc/quaternion.hpp \
		Include/glm/gtc/constants.hpp \
		Include/glm/gtc/constants.inl \
		Include/glm/gtc/quaternion.inl \
		Include/glm/gtc/type_ptr.inl \
		Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Crate.o Crate.cpp

Cube.o: Cube.cpp Utils.h \
		Include/glm/glm.hpp \
		Include/glm/core/_fixes.hpp \
		Include/glm/core/setup.hpp \
		Include/glm/core/_detail.hpp \
		Include/glm/core/_vectorize.hpp \
		Include/glm/core/type.hpp \
		Include/glm/core/type_half.hpp \
		Include/glm/core/type_half.inl \
		Include/glm/core/type_float.hpp \
		Include/glm/core/type_int.hpp \
		Include/glm/core/type_gentype.hpp \
		Include/glm/core/type_size.hpp \
		Include/glm/core/type_vec1.hpp \
		Include/glm/core/type_vec.hpp \
		Include/glm/core/_swizzle.hpp \
		Include/glm/core/_swizzle_func.hpp \
		Include/glm/core/type_vec1.inl \
		Include/glm/core/type_vec2.hpp \
		Include/glm/core/type_vec2.inl \
		Include/glm/core/type_vec3.hpp \
		Include/glm/core/type_vec3.inl \
		Include/glm/core/type_vec4.hpp \
		Include/glm/core/type_vec4.inl \
		Include/glm/core/type_mat2x2.hpp \
		Include/glm/core/type_mat.hpp \
		Include/glm/core/type_mat2x2.inl \
		Include/glm/core/type_mat2x3.hpp \
		Include/glm/core/type_mat2x3.inl \
		Include/glm/core/type_mat2x4.hpp \
		Include/glm/core/type_mat2x4.inl \
		Include/glm/core/type_mat3x2.hpp \
		Include/glm/core/type_mat3x2.inl \
		Include/glm/core/type_mat3x3.hpp \
		Include/glm/core/type_mat3x3.inl \
		Include/glm/core/type_mat3x4.hpp \
		Include/glm/core/type_mat3x4.inl \
		Include/glm/core/type_mat4x2.hpp \
		Include/glm/core/type_mat4x2.inl \
		Include/glm/core/type_mat4x3.hpp \
		Include/glm/core/type_mat4x3.inl \
		Include/glm/core/type_mat4x4.hpp \
		Include/glm/core/type_mat4x4.inl \
		Include/glm/core/func_trigonometric.hpp \
		Include/glm/core/func_trigonometric.inl \
		Include/glm/core/func_exponential.hpp \
		Include/glm/core/func_exponential.inl \
		Include/glm/core/func_common.hpp \
		Include/glm/core/func_common.inl \
		Include/glm/core/func_packing.hpp \
		Include/glm/core/func_packing.inl \
		Include/glm/core/func_geometric.hpp \
		Include/glm/core/func_geometric.inl \
		Include/glm/core/func_matrix.hpp \
		Include/glm/core/func_matrix.inl \
		Include/glm/core/func_vector_relational.hpp \
		Include/glm/core/func_vector_relational.inl \
		Include/glm/core/func_integer.hpp \
		Include/glm/core/func_integer.inl \
		Include/glm/core/func_noise.hpp \
		Include/glm/core/func_noise.inl \
		Include/OVR/LibOVR/Src/Kernel/OVR_Math.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Types.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_RefCount.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Allocator.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Std.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Alg.h \
		Cube.h \
		GraphicObject.h \
		Shader.h \
		Include/GL3/gl3.h \
		Include/glm/gtx/transform.hpp \
		Include/glm/gtc/matrix_transform.hpp \
		Include/glm/gtc/matrix_transform.inl \
		Include/glm/gtx/transform.inl \
		Include/glm/gtc/type_ptr.hpp \
		Include/glm/gtc/half_float.hpp \
		Include/glm/gtc/half_float.inl \
		Include/glm/gtc/quaternion.hpp \
		Include/glm/gtc/constants.hpp \
		Include/glm/gtc/constants.inl \
		Include/glm/gtc/quaternion.inl \
		Include/glm/gtc/type_ptr.inl \
		Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cube.o Cube.cpp

GraphicObject.o: GraphicObject.cpp GraphicObject.h \
		Include/glm/glm.hpp \
		Include/glm/core/_fixes.hpp \
		Include/glm/core/setup.hpp \
		Include/glm/core/_detail.hpp \
		Include/glm/core/_vectorize.hpp \
		Include/glm/core/type.hpp \
		Include/glm/core/type_half.hpp \
		Include/glm/core/type_half.inl \
		Include/glm/core/type_float.hpp \
		Include/glm/core/type_int.hpp \
		Include/glm/core/type_gentype.hpp \
		Include/glm/core/type_size.hpp \
		Include/glm/core/type_vec1.hpp \
		Include/glm/core/type_vec.hpp \
		Include/glm/core/_swizzle.hpp \
		Include/glm/core/_swizzle_func.hpp \
		Include/glm/core/type_vec1.inl \
		Include/glm/core/type_vec2.hpp \
		Include/glm/core/type_vec2.inl \
		Include/glm/core/type_vec3.hpp \
		Include/glm/core/type_vec3.inl \
		Include/glm/core/type_vec4.hpp \
		Include/glm/core/type_vec4.inl \
		Include/glm/core/type_mat2x2.hpp \
		Include/glm/core/type_mat.hpp \
		Include/glm/core/type_mat2x2.inl \
		Include/glm/core/type_mat2x3.hpp \
		Include/glm/core/type_mat2x3.inl \
		Include/glm/core/type_mat2x4.hpp \
		Include/glm/core/type_mat2x4.inl \
		Include/glm/core/type_mat3x2.hpp \
		Include/glm/core/type_mat3x2.inl \
		Include/glm/core/type_mat3x3.hpp \
		Include/glm/core/type_mat3x3.inl \
		Include/glm/core/type_mat3x4.hpp \
		Include/glm/core/type_mat3x4.inl \
		Include/glm/core/type_mat4x2.hpp \
		Include/glm/core/type_mat4x2.inl \
		Include/glm/core/type_mat4x3.hpp \
		Include/glm/core/type_mat4x3.inl \
		Include/glm/core/type_mat4x4.hpp \
		Include/glm/core/type_mat4x4.inl \
		Include/glm/core/func_trigonometric.hpp \
		Include/glm/core/func_trigonometric.inl \
		Include/glm/core/func_exponential.hpp \
		Include/glm/core/func_exponential.inl \
		Include/glm/core/func_common.hpp \
		Include/glm/core/func_common.inl \
		Include/glm/core/func_packing.hpp \
		Include/glm/core/func_packing.inl \
		Include/glm/core/func_geometric.hpp \
		Include/glm/core/func_geometric.inl \
		Include/glm/core/func_matrix.hpp \
		Include/glm/core/func_matrix.inl \
		Include/glm/core/func_vector_relational.hpp \
		Include/glm/core/func_vector_relational.inl \
		Include/glm/core/func_integer.hpp \
		Include/glm/core/func_integer.inl \
		Include/glm/core/func_noise.hpp \
		Include/glm/core/func_noise.inl \
		Shader.h \
		Include/GL3/gl3.h \
		Utils.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Math.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Types.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_RefCount.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Allocator.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Std.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Alg.h \
		Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GraphicObject.o GraphicObject.cpp

Input.o: Input.cpp Input.h \
		Include/glm/glm.hpp \
		Include/glm/core/_fixes.hpp \
		Include/glm/core/setup.hpp \
		Include/glm/core/_detail.hpp \
		Include/glm/core/_vectorize.hpp \
		Include/glm/core/type.hpp \
		Include/glm/core/type_half.hpp \
		Include/glm/core/type_half.inl \
		Include/glm/core/type_float.hpp \
		Include/glm/core/type_int.hpp \
		Include/glm/core/type_gentype.hpp \
		Include/glm/core/type_size.hpp \
		Include/glm/core/type_vec1.hpp \
		Include/glm/core/type_vec.hpp \
		Include/glm/core/_swizzle.hpp \
		Include/glm/core/_swizzle_func.hpp \
		Include/glm/core/type_vec1.inl \
		Include/glm/core/type_vec2.hpp \
		Include/glm/core/type_vec2.inl \
		Include/glm/core/type_vec3.hpp \
		Include/glm/core/type_vec3.inl \
		Include/glm/core/type_vec4.hpp \
		Include/glm/core/type_vec4.inl \
		Include/glm/core/type_mat2x2.hpp \
		Include/glm/core/type_mat.hpp \
		Include/glm/core/type_mat2x2.inl \
		Include/glm/core/type_mat2x3.hpp \
		Include/glm/core/type_mat2x3.inl \
		Include/glm/core/type_mat2x4.hpp \
		Include/glm/core/type_mat2x4.inl \
		Include/glm/core/type_mat3x2.hpp \
		Include/glm/core/type_mat3x2.inl \
		Include/glm/core/type_mat3x3.hpp \
		Include/glm/core/type_mat3x3.inl \
		Include/glm/core/type_mat3x4.hpp \
		Include/glm/core/type_mat3x4.inl \
		Include/glm/core/type_mat4x2.hpp \
		Include/glm/core/type_mat4x2.inl \
		Include/glm/core/type_mat4x3.hpp \
		Include/glm/core/type_mat4x3.inl \
		Include/glm/core/type_mat4x4.hpp \
		Include/glm/core/type_mat4x4.inl \
		Include/glm/core/func_trigonometric.hpp \
		Include/glm/core/func_trigonometric.inl \
		Include/glm/core/func_exponential.hpp \
		Include/glm/core/func_exponential.inl \
		Include/glm/core/func_common.hpp \
		Include/glm/core/func_common.inl \
		Include/glm/core/func_packing.hpp \
		Include/glm/core/func_packing.inl \
		Include/glm/core/func_geometric.hpp \
		Include/glm/core/func_geometric.inl \
		Include/glm/core/func_matrix.hpp \
		Include/glm/core/func_matrix.inl \
		Include/glm/core/func_vector_relational.hpp \
		Include/glm/core/func_vector_relational.inl \
		Include/glm/core/func_integer.hpp \
		Include/glm/core/func_integer.inl \
		Include/glm/core/func_noise.hpp \
		Include/glm/core/func_noise.inl \
		Oculus.h \
		Include/OVR/LibOVR/Include/OVR.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Allocator.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Types.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Log.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Math.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_RefCount.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Std.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Alg.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_System.h \
		Include/OVR/LibOVR/Src/OVR_Device.h \
		Include/OVR/LibOVR/Src/OVR_DeviceConstants.h \
		Include/OVR/LibOVR/Src/OVR_DeviceHandle.h \
		Include/OVR/LibOVR/Src/OVR_DeviceMessages.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Array.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_ContainerAllocator.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Color.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_String.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_UTF8Util.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Atomic.h \
		Include/OVR/LibOVR/Src/OVR_HIDDeviceBase.h \
		Include/OVR/LibOVR/Src/OVR_SensorFusion.h \
		Include/OVR/LibOVR/Src/OVR_SensorFilter.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Deque.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Timer.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Threads.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Lockless.h \
		Include/OVR/LibOVR/Src/OVR_Stereo.h \
		Include/OVR/LibOVR/Src/OVR_Profile.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_StringHash.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Hash.h \
		Include/OVR/LibOVR/Src/Util/Util_LatencyTest.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_List.h \
		Include/OVR/LibOVR/Src/Util/Util_Render_Stereo.h \
		Include/OVR/LibOVR/Src/Util/Util_Interface.h \
		Include/OVR/LibOVR/Src/OVR_CAPI.h \
		Include/OVR/LibOVR/Src/OVR_CAPI_GL.h \
		Include/GL3/gl3.h \
		Utils.h \
		Log.h \
		Scene.h \
		Include/glm/gtx/transform.hpp \
		Include/glm/gtc/matrix_transform.hpp \
		Include/glm/gtc/matrix_transform.inl \
		Include/glm/gtx/transform.inl \
		Include/glm/gtc/type_ptr.hpp \
		Include/glm/gtc/half_float.hpp \
		Include/glm/gtc/half_float.inl \
		Include/glm/gtc/quaternion.hpp \
		Include/glm/gtc/constants.hpp \
		Include/glm/gtc/constants.inl \
		Include/glm/gtc/quaternion.inl \
		Include/glm/gtc/type_ptr.inl \
		Shader.h \
		Include/Octree/octree.h \
		Include/Octree/array2d.h \
		Include/Octree/array.h \
		Include/Octree/shareddata.h \
		Include/Octree/tinyvector.h \
		Include/Octree/numtraits.h \
		Include/Octree/point3d.h \
		Include/Octree/octree.tcc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Input.o Input.cpp

Log.o: Log.cpp Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Log.o Log.cpp

main.o: main.cpp Log.h \
		Scene.h \
		Include/GL3/gl3.h \
		Include/glm/glm.hpp \
		Include/glm/core/_fixes.hpp \
		Include/glm/core/setup.hpp \
		Include/glm/core/_detail.hpp \
		Include/glm/core/_vectorize.hpp \
		Include/glm/core/type.hpp \
		Include/glm/core/type_half.hpp \
		Include/glm/core/type_half.inl \
		Include/glm/core/type_float.hpp \
		Include/glm/core/type_int.hpp \
		Include/glm/core/type_gentype.hpp \
		Include/glm/core/type_size.hpp \
		Include/glm/core/type_vec1.hpp \
		Include/glm/core/type_vec.hpp \
		Include/glm/core/_swizzle.hpp \
		Include/glm/core/_swizzle_func.hpp \
		Include/glm/core/type_vec1.inl \
		Include/glm/core/type_vec2.hpp \
		Include/glm/core/type_vec2.inl \
		Include/glm/core/type_vec3.hpp \
		Include/glm/core/type_vec3.inl \
		Include/glm/core/type_vec4.hpp \
		Include/glm/core/type_vec4.inl \
		Include/glm/core/type_mat2x2.hpp \
		Include/glm/core/type_mat.hpp \
		Include/glm/core/type_mat2x2.inl \
		Include/glm/core/type_mat2x3.hpp \
		Include/glm/core/type_mat2x3.inl \
		Include/glm/core/type_mat2x4.hpp \
		Include/glm/core/type_mat2x4.inl \
		Include/glm/core/type_mat3x2.hpp \
		Include/glm/core/type_mat3x2.inl \
		Include/glm/core/type_mat3x3.hpp \
		Include/glm/core/type_mat3x3.inl \
		Include/glm/core/type_mat3x4.hpp \
		Include/glm/core/type_mat3x4.inl \
		Include/glm/core/type_mat4x2.hpp \
		Include/glm/core/type_mat4x2.inl \
		Include/glm/core/type_mat4x3.hpp \
		Include/glm/core/type_mat4x3.inl \
		Include/glm/core/type_mat4x4.hpp \
		Include/glm/core/type_mat4x4.inl \
		Include/glm/core/func_trigonometric.hpp \
		Include/glm/core/func_trigonometric.inl \
		Include/glm/core/func_exponential.hpp \
		Include/glm/core/func_exponential.inl \
		Include/glm/core/func_common.hpp \
		Include/glm/core/func_common.inl \
		Include/glm/core/func_packing.hpp \
		Include/glm/core/func_packing.inl \
		Include/glm/core/func_geometric.hpp \
		Include/glm/core/func_geometric.inl \
		Include/glm/core/func_matrix.hpp \
		Include/glm/core/func_matrix.inl \
		Include/glm/core/func_vector_relational.hpp \
		Include/glm/core/func_vector_relational.inl \
		Include/glm/core/func_integer.hpp \
		Include/glm/core/func_integer.inl \
		Include/glm/core/func_noise.hpp \
		Include/glm/core/func_noise.inl \
		Include/glm/gtx/transform.hpp \
		Include/glm/gtc/matrix_transform.hpp \
		Include/glm/gtc/matrix_transform.inl \
		Include/glm/gtx/transform.inl \
		Include/glm/gtc/type_ptr.hpp \
		Include/glm/gtc/half_float.hpp \
		Include/glm/gtc/half_float.inl \
		Include/glm/gtc/quaternion.hpp \
		Include/glm/gtc/constants.hpp \
		Include/glm/gtc/constants.inl \
		Include/glm/gtc/quaternion.inl \
		Include/glm/gtc/type_ptr.inl \
		Shader.h \
		Include/Octree/octree.h \
		Include/Octree/array2d.h \
		Include/Octree/array.h \
		Include/Octree/shareddata.h \
		Include/Octree/tinyvector.h \
		Include/Octree/numtraits.h \
		Include/Octree/point3d.h \
		Include/Octree/octree.tcc \
		Oculus.h \
		Include/OVR/LibOVR/Include/OVR.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Allocator.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Types.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Log.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Math.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_RefCount.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Std.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Alg.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_System.h \
		Include/OVR/LibOVR/Src/OVR_Device.h \
		Include/OVR/LibOVR/Src/OVR_DeviceConstants.h \
		Include/OVR/LibOVR/Src/OVR_DeviceHandle.h \
		Include/OVR/LibOVR/Src/OVR_DeviceMessages.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Array.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_ContainerAllocator.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Color.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_String.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_UTF8Util.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Atomic.h \
		Include/OVR/LibOVR/Src/OVR_HIDDeviceBase.h \
		Include/OVR/LibOVR/Src/OVR_SensorFusion.h \
		Include/OVR/LibOVR/Src/OVR_SensorFilter.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Deque.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Timer.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Threads.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Lockless.h \
		Include/OVR/LibOVR/Src/OVR_Stereo.h \
		Include/OVR/LibOVR/Src/OVR_Profile.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_StringHash.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Hash.h \
		Include/OVR/LibOVR/Src/Util/Util_LatencyTest.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_List.h \
		Include/OVR/LibOVR/Src/Util/Util_Render_Stereo.h \
		Include/OVR/LibOVR/Src/Util/Util_Interface.h \
		Include/OVR/LibOVR/Src/OVR_CAPI.h \
		Include/OVR/LibOVR/Src/OVR_CAPI_GL.h \
		Utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Oculus.o: Oculus.cpp Oculus.h \
		Include/OVR/LibOVR/Include/OVR.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Allocator.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Types.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Log.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Math.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_RefCount.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Std.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Alg.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_System.h \
		Include/OVR/LibOVR/Src/OVR_Device.h \
		Include/OVR/LibOVR/Src/OVR_DeviceConstants.h \
		Include/OVR/LibOVR/Src/OVR_DeviceHandle.h \
		Include/OVR/LibOVR/Src/OVR_DeviceMessages.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Array.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_ContainerAllocator.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Color.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_String.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_UTF8Util.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Atomic.h \
		Include/OVR/LibOVR/Src/OVR_HIDDeviceBase.h \
		Include/OVR/LibOVR/Src/OVR_SensorFusion.h \
		Include/OVR/LibOVR/Src/OVR_SensorFilter.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Deque.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Timer.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Threads.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Lockless.h \
		Include/OVR/LibOVR/Src/OVR_Stereo.h \
		Include/OVR/LibOVR/Src/OVR_Profile.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_StringHash.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Hash.h \
		Include/OVR/LibOVR/Src/Util/Util_LatencyTest.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_List.h \
		Include/OVR/LibOVR/Src/Util/Util_Render_Stereo.h \
		Include/OVR/LibOVR/Src/Util/Util_Interface.h \
		Include/OVR/LibOVR/Src/OVR_CAPI.h \
		Include/OVR/LibOVR/Src/OVR_CAPI_GL.h \
		Include/GL3/gl3.h \
		Include/glm/glm.hpp \
		Include/glm/core/_fixes.hpp \
		Include/glm/core/setup.hpp \
		Include/glm/core/_detail.hpp \
		Include/glm/core/_vectorize.hpp \
		Include/glm/core/type.hpp \
		Include/glm/core/type_half.hpp \
		Include/glm/core/type_half.inl \
		Include/glm/core/type_float.hpp \
		Include/glm/core/type_int.hpp \
		Include/glm/core/type_gentype.hpp \
		Include/glm/core/type_size.hpp \
		Include/glm/core/type_vec1.hpp \
		Include/glm/core/type_vec.hpp \
		Include/glm/core/_swizzle.hpp \
		Include/glm/core/_swizzle_func.hpp \
		Include/glm/core/type_vec1.inl \
		Include/glm/core/type_vec2.hpp \
		Include/glm/core/type_vec2.inl \
		Include/glm/core/type_vec3.hpp \
		Include/glm/core/type_vec3.inl \
		Include/glm/core/type_vec4.hpp \
		Include/glm/core/type_vec4.inl \
		Include/glm/core/type_mat2x2.hpp \
		Include/glm/core/type_mat.hpp \
		Include/glm/core/type_mat2x2.inl \
		Include/glm/core/type_mat2x3.hpp \
		Include/glm/core/type_mat2x3.inl \
		Include/glm/core/type_mat2x4.hpp \
		Include/glm/core/type_mat2x4.inl \
		Include/glm/core/type_mat3x2.hpp \
		Include/glm/core/type_mat3x2.inl \
		Include/glm/core/type_mat3x3.hpp \
		Include/glm/core/type_mat3x3.inl \
		Include/glm/core/type_mat3x4.hpp \
		Include/glm/core/type_mat3x4.inl \
		Include/glm/core/type_mat4x2.hpp \
		Include/glm/core/type_mat4x2.inl \
		Include/glm/core/type_mat4x3.hpp \
		Include/glm/core/type_mat4x3.inl \
		Include/glm/core/type_mat4x4.hpp \
		Include/glm/core/type_mat4x4.inl \
		Include/glm/core/func_trigonometric.hpp \
		Include/glm/core/func_trigonometric.inl \
		Include/glm/core/func_exponential.hpp \
		Include/glm/core/func_exponential.inl \
		Include/glm/core/func_common.hpp \
		Include/glm/core/func_common.inl \
		Include/glm/core/func_packing.hpp \
		Include/glm/core/func_packing.inl \
		Include/glm/core/func_geometric.hpp \
		Include/glm/core/func_geometric.inl \
		Include/glm/core/func_matrix.hpp \
		Include/glm/core/func_matrix.inl \
		Include/glm/core/func_vector_relational.hpp \
		Include/glm/core/func_vector_relational.inl \
		Include/glm/core/func_integer.hpp \
		Include/glm/core/func_integer.inl \
		Include/glm/core/func_noise.hpp \
		Include/glm/core/func_noise.inl \
		Utils.h \
		Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Oculus.o Oculus.cpp

Plane.o: Plane.cpp Plane.h \
		Include/glm/glm.hpp \
		Include/glm/core/_fixes.hpp \
		Include/glm/core/setup.hpp \
		Include/glm/core/_detail.hpp \
		Include/glm/core/_vectorize.hpp \
		Include/glm/core/type.hpp \
		Include/glm/core/type_half.hpp \
		Include/glm/core/type_half.inl \
		Include/glm/core/type_float.hpp \
		Include/glm/core/type_int.hpp \
		Include/glm/core/type_gentype.hpp \
		Include/glm/core/type_size.hpp \
		Include/glm/core/type_vec1.hpp \
		Include/glm/core/type_vec.hpp \
		Include/glm/core/_swizzle.hpp \
		Include/glm/core/_swizzle_func.hpp \
		Include/glm/core/type_vec1.inl \
		Include/glm/core/type_vec2.hpp \
		Include/glm/core/type_vec2.inl \
		Include/glm/core/type_vec3.hpp \
		Include/glm/core/type_vec3.inl \
		Include/glm/core/type_vec4.hpp \
		Include/glm/core/type_vec4.inl \
		Include/glm/core/type_mat2x2.hpp \
		Include/glm/core/type_mat.hpp \
		Include/glm/core/type_mat2x2.inl \
		Include/glm/core/type_mat2x3.hpp \
		Include/glm/core/type_mat2x3.inl \
		Include/glm/core/type_mat2x4.hpp \
		Include/glm/core/type_mat2x4.inl \
		Include/glm/core/type_mat3x2.hpp \
		Include/glm/core/type_mat3x2.inl \
		Include/glm/core/type_mat3x3.hpp \
		Include/glm/core/type_mat3x3.inl \
		Include/glm/core/type_mat3x4.hpp \
		Include/glm/core/type_mat3x4.inl \
		Include/glm/core/type_mat4x2.hpp \
		Include/glm/core/type_mat4x2.inl \
		Include/glm/core/type_mat4x3.hpp \
		Include/glm/core/type_mat4x3.inl \
		Include/glm/core/type_mat4x4.hpp \
		Include/glm/core/type_mat4x4.inl \
		Include/glm/core/func_trigonometric.hpp \
		Include/glm/core/func_trigonometric.inl \
		Include/glm/core/func_exponential.hpp \
		Include/glm/core/func_exponential.inl \
		Include/glm/core/func_common.hpp \
		Include/glm/core/func_common.inl \
		Include/glm/core/func_packing.hpp \
		Include/glm/core/func_packing.inl \
		Include/glm/core/func_geometric.hpp \
		Include/glm/core/func_geometric.inl \
		Include/glm/core/func_matrix.hpp \
		Include/glm/core/func_matrix.inl \
		Include/glm/core/func_vector_relational.hpp \
		Include/glm/core/func_vector_relational.inl \
		Include/glm/core/func_integer.hpp \
		Include/glm/core/func_integer.inl \
		Include/glm/core/func_noise.hpp \
		Include/glm/core/func_noise.inl \
		GraphicObject.h \
		Shader.h \
		Include/GL3/gl3.h \
		Utils.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Math.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Types.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_RefCount.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Allocator.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Std.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Alg.h \
		Texture.h \
		Include/glm/gtx/transform.hpp \
		Include/glm/gtc/matrix_transform.hpp \
		Include/glm/gtc/matrix_transform.inl \
		Include/glm/gtx/transform.inl \
		Include/glm/gtc/type_ptr.hpp \
		Include/glm/gtc/half_float.hpp \
		Include/glm/gtc/half_float.inl \
		Include/glm/gtc/quaternion.hpp \
		Include/glm/gtc/constants.hpp \
		Include/glm/gtc/constants.inl \
		Include/glm/gtc/quaternion.inl \
		Include/glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Plane.o Plane.cpp

Scene.o: Scene.cpp Scene.h \
		Include/GL3/gl3.h \
		Include/glm/glm.hpp \
		Include/glm/core/_fixes.hpp \
		Include/glm/core/setup.hpp \
		Include/glm/core/_detail.hpp \
		Include/glm/core/_vectorize.hpp \
		Include/glm/core/type.hpp \
		Include/glm/core/type_half.hpp \
		Include/glm/core/type_half.inl \
		Include/glm/core/type_float.hpp \
		Include/glm/core/type_int.hpp \
		Include/glm/core/type_gentype.hpp \
		Include/glm/core/type_size.hpp \
		Include/glm/core/type_vec1.hpp \
		Include/glm/core/type_vec.hpp \
		Include/glm/core/_swizzle.hpp \
		Include/glm/core/_swizzle_func.hpp \
		Include/glm/core/type_vec1.inl \
		Include/glm/core/type_vec2.hpp \
		Include/glm/core/type_vec2.inl \
		Include/glm/core/type_vec3.hpp \
		Include/glm/core/type_vec3.inl \
		Include/glm/core/type_vec4.hpp \
		Include/glm/core/type_vec4.inl \
		Include/glm/core/type_mat2x2.hpp \
		Include/glm/core/type_mat.hpp \
		Include/glm/core/type_mat2x2.inl \
		Include/glm/core/type_mat2x3.hpp \
		Include/glm/core/type_mat2x3.inl \
		Include/glm/core/type_mat2x4.hpp \
		Include/glm/core/type_mat2x4.inl \
		Include/glm/core/type_mat3x2.hpp \
		Include/glm/core/type_mat3x2.inl \
		Include/glm/core/type_mat3x3.hpp \
		Include/glm/core/type_mat3x3.inl \
		Include/glm/core/type_mat3x4.hpp \
		Include/glm/core/type_mat3x4.inl \
		Include/glm/core/type_mat4x2.hpp \
		Include/glm/core/type_mat4x2.inl \
		Include/glm/core/type_mat4x3.hpp \
		Include/glm/core/type_mat4x3.inl \
		Include/glm/core/type_mat4x4.hpp \
		Include/glm/core/type_mat4x4.inl \
		Include/glm/core/func_trigonometric.hpp \
		Include/glm/core/func_trigonometric.inl \
		Include/glm/core/func_exponential.hpp \
		Include/glm/core/func_exponential.inl \
		Include/glm/core/func_common.hpp \
		Include/glm/core/func_common.inl \
		Include/glm/core/func_packing.hpp \
		Include/glm/core/func_packing.inl \
		Include/glm/core/func_geometric.hpp \
		Include/glm/core/func_geometric.inl \
		Include/glm/core/func_matrix.hpp \
		Include/glm/core/func_matrix.inl \
		Include/glm/core/func_vector_relational.hpp \
		Include/glm/core/func_vector_relational.inl \
		Include/glm/core/func_integer.hpp \
		Include/glm/core/func_integer.inl \
		Include/glm/core/func_noise.hpp \
		Include/glm/core/func_noise.inl \
		Include/glm/gtx/transform.hpp \
		Include/glm/gtc/matrix_transform.hpp \
		Include/glm/gtc/matrix_transform.inl \
		Include/glm/gtx/transform.inl \
		Include/glm/gtc/type_ptr.hpp \
		Include/glm/gtc/half_float.hpp \
		Include/glm/gtc/half_float.inl \
		Include/glm/gtc/quaternion.hpp \
		Include/glm/gtc/constants.hpp \
		Include/glm/gtc/constants.inl \
		Include/glm/gtc/quaternion.inl \
		Include/glm/gtc/type_ptr.inl \
		Shader.h \
		Include/Octree/octree.h \
		Include/Octree/array2d.h \
		Include/Octree/array.h \
		Include/Octree/shareddata.h \
		Include/Octree/tinyvector.h \
		Include/Octree/numtraits.h \
		Include/Octree/point3d.h \
		Include/Octree/octree.tcc \
		Oculus.h \
		Include/OVR/LibOVR/Include/OVR.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Allocator.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Types.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Log.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Math.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_RefCount.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Std.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Alg.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_System.h \
		Include/OVR/LibOVR/Src/OVR_Device.h \
		Include/OVR/LibOVR/Src/OVR_DeviceConstants.h \
		Include/OVR/LibOVR/Src/OVR_DeviceHandle.h \
		Include/OVR/LibOVR/Src/OVR_DeviceMessages.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Array.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_ContainerAllocator.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Color.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_String.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_UTF8Util.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Atomic.h \
		Include/OVR/LibOVR/Src/OVR_HIDDeviceBase.h \
		Include/OVR/LibOVR/Src/OVR_SensorFusion.h \
		Include/OVR/LibOVR/Src/OVR_SensorFilter.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Deque.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Timer.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Threads.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Lockless.h \
		Include/OVR/LibOVR/Src/OVR_Stereo.h \
		Include/OVR/LibOVR/Src/OVR_Profile.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_StringHash.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Hash.h \
		Include/OVR/LibOVR/Src/Util/Util_LatencyTest.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_List.h \
		Include/OVR/LibOVR/Src/Util/Util_Render_Stereo.h \
		Include/OVR/LibOVR/Src/Util/Util_Interface.h \
		Include/OVR/LibOVR/Src/OVR_CAPI.h \
		Include/OVR/LibOVR/Src/OVR_CAPI_GL.h \
		Utils.h \
		Log.h \
		Cube.h \
		GraphicObject.h \
		Input.h \
		Crate.h \
		Texture.h \
		Camera.h \
		Plane.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Scene.o Scene.cpp

Shader.o: Shader.cpp Shader.h \
		Include/GL3/gl3.h \
		Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Shader.o Shader.cpp

Texture.o: Texture.cpp Texture.h \
		Include/GL3/gl3.h \
		Utils.h \
		Include/glm/glm.hpp \
		Include/glm/core/_fixes.hpp \
		Include/glm/core/setup.hpp \
		Include/glm/core/_detail.hpp \
		Include/glm/core/_vectorize.hpp \
		Include/glm/core/type.hpp \
		Include/glm/core/type_half.hpp \
		Include/glm/core/type_half.inl \
		Include/glm/core/type_float.hpp \
		Include/glm/core/type_int.hpp \
		Include/glm/core/type_gentype.hpp \
		Include/glm/core/type_size.hpp \
		Include/glm/core/type_vec1.hpp \
		Include/glm/core/type_vec.hpp \
		Include/glm/core/_swizzle.hpp \
		Include/glm/core/_swizzle_func.hpp \
		Include/glm/core/type_vec1.inl \
		Include/glm/core/type_vec2.hpp \
		Include/glm/core/type_vec2.inl \
		Include/glm/core/type_vec3.hpp \
		Include/glm/core/type_vec3.inl \
		Include/glm/core/type_vec4.hpp \
		Include/glm/core/type_vec4.inl \
		Include/glm/core/type_mat2x2.hpp \
		Include/glm/core/type_mat.hpp \
		Include/glm/core/type_mat2x2.inl \
		Include/glm/core/type_mat2x3.hpp \
		Include/glm/core/type_mat2x3.inl \
		Include/glm/core/type_mat2x4.hpp \
		Include/glm/core/type_mat2x4.inl \
		Include/glm/core/type_mat3x2.hpp \
		Include/glm/core/type_mat3x2.inl \
		Include/glm/core/type_mat3x3.hpp \
		Include/glm/core/type_mat3x3.inl \
		Include/glm/core/type_mat3x4.hpp \
		Include/glm/core/type_mat3x4.inl \
		Include/glm/core/type_mat4x2.hpp \
		Include/glm/core/type_mat4x2.inl \
		Include/glm/core/type_mat4x3.hpp \
		Include/glm/core/type_mat4x3.inl \
		Include/glm/core/type_mat4x4.hpp \
		Include/glm/core/type_mat4x4.inl \
		Include/glm/core/func_trigonometric.hpp \
		Include/glm/core/func_trigonometric.inl \
		Include/glm/core/func_exponential.hpp \
		Include/glm/core/func_exponential.inl \
		Include/glm/core/func_common.hpp \
		Include/glm/core/func_common.inl \
		Include/glm/core/func_packing.hpp \
		Include/glm/core/func_packing.inl \
		Include/glm/core/func_geometric.hpp \
		Include/glm/core/func_geometric.inl \
		Include/glm/core/func_matrix.hpp \
		Include/glm/core/func_matrix.inl \
		Include/glm/core/func_vector_relational.hpp \
		Include/glm/core/func_vector_relational.inl \
		Include/glm/core/func_integer.hpp \
		Include/glm/core/func_integer.inl \
		Include/glm/core/func_noise.hpp \
		Include/glm/core/func_noise.inl \
		Include/OVR/LibOVR/Src/Kernel/OVR_Math.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Types.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_RefCount.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Allocator.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Std.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Alg.h \
		Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Texture.o Texture.cpp

Utils.o: Utils.cpp Utils.h \
		Include/glm/glm.hpp \
		Include/glm/core/_fixes.hpp \
		Include/glm/core/setup.hpp \
		Include/glm/core/_detail.hpp \
		Include/glm/core/_vectorize.hpp \
		Include/glm/core/type.hpp \
		Include/glm/core/type_half.hpp \
		Include/glm/core/type_half.inl \
		Include/glm/core/type_float.hpp \
		Include/glm/core/type_int.hpp \
		Include/glm/core/type_gentype.hpp \
		Include/glm/core/type_size.hpp \
		Include/glm/core/type_vec1.hpp \
		Include/glm/core/type_vec.hpp \
		Include/glm/core/_swizzle.hpp \
		Include/glm/core/_swizzle_func.hpp \
		Include/glm/core/type_vec1.inl \
		Include/glm/core/type_vec2.hpp \
		Include/glm/core/type_vec2.inl \
		Include/glm/core/type_vec3.hpp \
		Include/glm/core/type_vec3.inl \
		Include/glm/core/type_vec4.hpp \
		Include/glm/core/type_vec4.inl \
		Include/glm/core/type_mat2x2.hpp \
		Include/glm/core/type_mat.hpp \
		Include/glm/core/type_mat2x2.inl \
		Include/glm/core/type_mat2x3.hpp \
		Include/glm/core/type_mat2x3.inl \
		Include/glm/core/type_mat2x4.hpp \
		Include/glm/core/type_mat2x4.inl \
		Include/glm/core/type_mat3x2.hpp \
		Include/glm/core/type_mat3x2.inl \
		Include/glm/core/type_mat3x3.hpp \
		Include/glm/core/type_mat3x3.inl \
		Include/glm/core/type_mat3x4.hpp \
		Include/glm/core/type_mat3x4.inl \
		Include/glm/core/type_mat4x2.hpp \
		Include/glm/core/type_mat4x2.inl \
		Include/glm/core/type_mat4x3.hpp \
		Include/glm/core/type_mat4x3.inl \
		Include/glm/core/type_mat4x4.hpp \
		Include/glm/core/type_mat4x4.inl \
		Include/glm/core/func_trigonometric.hpp \
		Include/glm/core/func_trigonometric.inl \
		Include/glm/core/func_exponential.hpp \
		Include/glm/core/func_exponential.inl \
		Include/glm/core/func_common.hpp \
		Include/glm/core/func_common.inl \
		Include/glm/core/func_packing.hpp \
		Include/glm/core/func_packing.inl \
		Include/glm/core/func_geometric.hpp \
		Include/glm/core/func_geometric.inl \
		Include/glm/core/func_matrix.hpp \
		Include/glm/core/func_matrix.inl \
		Include/glm/core/func_vector_relational.hpp \
		Include/glm/core/func_vector_relational.inl \
		Include/glm/core/func_integer.hpp \
		Include/glm/core/func_integer.inl \
		Include/glm/core/func_noise.hpp \
		Include/glm/core/func_noise.inl \
		Include/OVR/LibOVR/Src/Kernel/OVR_Math.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Types.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_RefCount.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Allocator.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Std.h \
		Include/OVR/LibOVR/Src/Kernel/OVR_Alg.h \
		Log.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Utils.o Utils.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

