SOURCES += \
    Camera.cpp \
    Crate.cpp \
    Cube.cpp \
    GraphicObject.cpp \
    Input.cpp \
    main.cpp \
    Oculus.cpp \
    Plane.cpp \
    Scene.cpp \
    Shader.cpp \
    Texture.cpp \
    Utils.cpp \
    build/CMakeFiles/3.2.2/CompilerIdCXX/CMakeCXXCompilerId.cpp \
    build/CMakeFiles/feature_tests.cxx \
    Include/glm/core/dummy.cpp \
    Include/Octree/demo.cpp \
    Include/OVR/3rdParty/EDID/edid.cpp \
    Include/OVR/3rdParty/TinyXml/tinyxml2.cpp \
    Include/OVR/LibOVR/Src/CAPI/GL/CAPI_GL_DistortionRenderer.cpp \
    Include/OVR/LibOVR/Src/CAPI/GL/CAPI_GL_Util.cpp \
    Include/OVR/LibOVR/Src/CAPI/CAPI_DistortionRenderer.cpp \
    Include/OVR/LibOVR/Src/CAPI/CAPI_FrameTimeManager.cpp \
    Include/OVR/LibOVR/Src/CAPI/CAPI_GlobalState.cpp \
    Include/OVR/LibOVR/Src/CAPI/CAPI_HMDRenderState.cpp \
    Include/OVR/LibOVR/Src/CAPI/CAPI_HMDState.cpp \
    Include/OVR/LibOVR/Src/Kernel/OVR_Alg.cpp \
    Include/OVR/LibOVR/Src/Kernel/OVR_Allocator.cpp \
    Include/OVR/LibOVR/Src/Kernel/OVR_Atomic.cpp \
    Include/OVR/LibOVR/Src/Kernel/OVR_File.cpp \
    Include/OVR/LibOVR/Src/Kernel/OVR_FileFILE.cpp \
    Include/OVR/LibOVR/Src/Kernel/OVR_Lockless.cpp \
    Include/OVR/LibOVR/Src/Kernel/OVR_Log.cpp \
    Include/OVR/LibOVR/Src/Kernel/OVR_Math.cpp \
    Include/OVR/LibOVR/Src/Kernel/OVR_RefCount.cpp \
    Include/OVR/LibOVR/Src/Kernel/OVR_Std.cpp \
    Include/OVR/LibOVR/Src/Kernel/OVR_String.cpp \
    Include/OVR/LibOVR/Src/Kernel/OVR_String_FormatUtil.cpp \
    Include/OVR/LibOVR/Src/Kernel/OVR_String_PathUtil.cpp \
    Include/OVR/LibOVR/Src/Kernel/OVR_SysFile.cpp \
    Include/OVR/LibOVR/Src/Kernel/OVR_System.cpp \
    Include/OVR/LibOVR/Src/Kernel/OVR_ThreadsPthread.cpp \
    Include/OVR/LibOVR/Src/Kernel/OVR_ThreadsWinAPI.cpp \
    Include/OVR/LibOVR/Src/Kernel/OVR_Timer.cpp \
    Include/OVR/LibOVR/Src/Kernel/OVR_UTF8Util.cpp \
    Include/OVR/LibOVR/Src/Util/Util_ImageWindow.cpp \
    Include/OVR/LibOVR/Src/Util/Util_Interface.cpp \
    Include/OVR/LibOVR/Src/Util/Util_LatencyTest.cpp \
    Include/OVR/LibOVR/Src/Util/Util_LatencyTest2.cpp \
    Include/OVR/LibOVR/Src/Util/Util_MagCalibration.cpp \
    Include/OVR/LibOVR/Src/Util/Util_Render_Stereo.cpp \
    Include/OVR/LibOVR/Src/OVR_CAPI.cpp \
    Include/OVR/LibOVR/Src/OVR_Common_HMDDevice.cpp \
    Include/OVR/LibOVR/Src/OVR_DeviceHandle.cpp \
    Include/OVR/LibOVR/Src/OVR_DeviceImpl.cpp \
    Include/OVR/LibOVR/Src/OVR_JSON.cpp \
    Include/OVR/LibOVR/Src/OVR_LatencyTestImpl.cpp \
    Include/OVR/LibOVR/Src/OVR_Linux_DeviceManager.cpp \
    Include/OVR/LibOVR/Src/OVR_Linux_HIDDevice.cpp \
    Include/OVR/LibOVR/Src/OVR_Linux_HMDDevice.cpp \
    Include/OVR/LibOVR/Src/OVR_Linux_SensorDevice.cpp \
    Include/OVR/LibOVR/Src/OVR_OSX_DeviceManager.cpp \
    Include/OVR/LibOVR/Src/OVR_OSX_HIDDevice.cpp \
    Include/OVR/LibOVR/Src/OVR_OSX_HMDDevice.cpp \
    Include/OVR/LibOVR/Src/OVR_OSX_SensorDevice.cpp \
    Include/OVR/LibOVR/Src/OVR_Profile.cpp \
    Include/OVR/LibOVR/Src/OVR_Recording.cpp \
    Include/OVR/LibOVR/Src/OVR_Sensor2Impl.cpp \
    Include/OVR/LibOVR/Src/OVR_SensorCalibration.cpp \
    Include/OVR/LibOVR/Src/OVR_SensorFilter.cpp \
    Include/OVR/LibOVR/Src/OVR_SensorFusion.cpp \
    Include/OVR/LibOVR/Src/OVR_SensorImpl.cpp \
    Include/OVR/LibOVR/Src/OVR_SensorImpl_Common.cpp \
    Include/OVR/LibOVR/Src/OVR_SensorTimeFilter.cpp \
    Include/OVR/LibOVR/Src/OVR_Stereo.cpp \
    Include/OVR/LibOVR/Src/OVR_ThreadCommandQueue.cpp \
    Include/OVR/LibOVR/Src/OVR_Win32_DeviceManager.cpp \
    Include/OVR/LibOVR/Src/OVR_Win32_DeviceStatus.cpp \
    Include/OVR/LibOVR/Src/OVR_Win32_HIDDevice.cpp \
    Include/OVR/LibOVR/Src/OVR_Win32_HMDDevice.cpp \
    Include/OVR/LibOVR/Src/OVR_Win32_SensorDevice.cpp \
    spdlog/bench/boost-bench-mt.cpp \
    spdlog/bench/boost-bench.cpp \
    spdlog/bench/easylogging-bench-mt.cpp \
    spdlog/bench/easylogging-bench.cpp \
    spdlog/bench/g2log-async.cpp \
    spdlog/bench/glog-bench-mt.cpp \
    spdlog/bench/glog-bench.cpp \
    spdlog/bench/spdlog-async.cpp \
    spdlog/bench/spdlog-bench-mt.cpp \
    spdlog/bench/spdlog-bench.cpp \
    spdlog/bench/zf_log-bench-mt.cpp \
    spdlog/bench/zf_log-bench.cpp \
    spdlog/example/bench.cpp \
    spdlog/example/example.cpp \
    spdlog/include/spdlog/details/format.cc \
    spdlog/tests/file_helper.cpp \
    spdlog/tests/file_log.cpp \
    spdlog/tests/format.cpp \
    spdlog/tests/main.cpp \
    spdlog/tests/registry.cpp \
    spdlog/tests/utils.cpp \
    build/CMakeFiles/3.2.2/CompilerIdC/CMakeCCompilerId.c \
    build/CMakeFiles/feature_tests.c

HEADERS += \
    Include/GL3/gl3.h \
    Include/glm/core/_detail.hpp \
    Include/glm/core/_fixes.hpp \
    Include/glm/core/_swizzle.hpp \
    Include/glm/core/_swizzle_func.hpp \
    Include/glm/core/_vectorize.hpp \
    Include/glm/core/func_common.hpp \
    Include/glm/core/func_exponential.hpp \
    Include/glm/core/func_geometric.hpp \
    Include/glm/core/func_integer.hpp \
    Include/glm/core/func_matrix.hpp \
    Include/glm/core/func_noise.hpp \
    Include/glm/core/func_packing.hpp \
    Include/glm/core/func_trigonometric.hpp \
    Include/glm/core/func_vector_relational.hpp \
    Include/glm/core/hint.hpp \
    Include/glm/core/intrinsic_common.hpp \
    Include/glm/core/intrinsic_exponential.hpp \
    Include/glm/core/intrinsic_geometric.hpp \
    Include/glm/core/intrinsic_matrix.hpp \
    Include/glm/core/intrinsic_trigonometric.hpp \
    Include/glm/core/intrinsic_vector_relational.hpp \
    Include/glm/core/setup.hpp \
    Include/glm/core/type.hpp \
    Include/glm/core/type_float.hpp \
    Include/glm/core/type_gentype.hpp \
    Include/glm/core/type_half.hpp \
    Include/glm/core/type_int.hpp \
    Include/glm/core/type_mat.hpp \
    Include/glm/core/type_mat2x2.hpp \
    Include/glm/core/type_mat2x3.hpp \
    Include/glm/core/type_mat2x4.hpp \
    Include/glm/core/type_mat3x2.hpp \
    Include/glm/core/type_mat3x3.hpp \
    Include/glm/core/type_mat3x4.hpp \
    Include/glm/core/type_mat4x2.hpp \
    Include/glm/core/type_mat4x3.hpp \
    Include/glm/core/type_mat4x4.hpp \
    Include/glm/core/type_size.hpp \
    Include/glm/core/type_vec.hpp \
    Include/glm/core/type_vec1.hpp \
    Include/glm/core/type_vec2.hpp \
    Include/glm/core/type_vec3.hpp \
    Include/glm/core/type_vec4.hpp \
    Include/glm/gtc/constants.hpp \
    Include/glm/gtc/epsilon.hpp \
    Include/glm/gtc/half_float.hpp \
    Include/glm/gtc/matrix_access.hpp \
    Include/glm/gtc/matrix_integer.hpp \
    Include/glm/gtc/matrix_inverse.hpp \
    Include/glm/gtc/matrix_transform.hpp \
    Include/glm/gtc/noise.hpp \
    Include/glm/gtc/quaternion.hpp \
    Include/glm/gtc/random.hpp \
    Include/glm/gtc/reciprocal.hpp \
    Include/glm/gtc/swizzle.hpp \
    Include/glm/gtc/type_precision.hpp \
    Include/glm/gtc/type_ptr.hpp \
    Include/glm/gtc/ulp.hpp \
    Include/glm/gtx/associated_min_max.hpp \
    Include/glm/gtx/bit.hpp \
    Include/glm/gtx/closest_point.hpp \
    Include/glm/gtx/color_cast.hpp \
    Include/glm/gtx/color_space.hpp \
    Include/glm/gtx/color_space_YCoCg.hpp \
    Include/glm/gtx/compatibility.hpp \
    Include/glm/gtx/component_wise.hpp \
    Include/glm/gtx/constants.hpp \
    Include/glm/gtx/epsilon.hpp \
    Include/glm/gtx/euler_angles.hpp \
    Include/glm/gtx/extend.hpp \
    Include/glm/gtx/extented_min_max.hpp \
    Include/glm/gtx/fast_exponential.hpp \
    Include/glm/gtx/fast_square_root.hpp \
    Include/glm/gtx/fast_trigonometry.hpp \
    Include/glm/gtx/gradient_paint.hpp \
    Include/glm/gtx/handed_coordinate_space.hpp \
    Include/glm/gtx/inertia.hpp \
    Include/glm/gtx/int_10_10_10_2.hpp \
    Include/glm/gtx/integer.hpp \
    Include/glm/gtx/intersect.hpp \
    Include/glm/gtx/log_base.hpp \
    Include/glm/gtx/matrix_cross_product.hpp \
    Include/glm/gtx/matrix_interpolation.hpp \
    Include/glm/gtx/matrix_major_storage.hpp \
    Include/glm/gtx/matrix_operation.hpp \
    Include/glm/gtx/matrix_query.hpp \
    Include/glm/gtx/mixed_product.hpp \
    Include/glm/gtx/multiple.hpp \
    Include/glm/gtx/noise.hpp \
    Include/glm/gtx/norm.hpp \
    Include/glm/gtx/normal.hpp \
    Include/glm/gtx/normalize_dot.hpp \
    Include/glm/gtx/number_precision.hpp \
    Include/glm/gtx/ocl_type.hpp \
    Include/glm/gtx/optimum_pow.hpp \
    Include/glm/gtx/orthonormalize.hpp \
    Include/glm/gtx/perpendicular.hpp \
    Include/glm/gtx/polar_coordinates.hpp \
    Include/glm/gtx/projection.hpp \
    Include/glm/gtx/quaternion.hpp \
    Include/glm/gtx/random.hpp \
    Include/glm/gtx/raw_data.hpp \
    Include/glm/gtx/reciprocal.hpp \
    Include/glm/gtx/rotate_vector.hpp \
    Include/glm/gtx/simd_mat4.hpp \
    Include/glm/gtx/simd_vec4.hpp \
    Include/glm/gtx/spline.hpp \
    Include/glm/gtx/std_based_type.hpp \
    Include/glm/gtx/string_cast.hpp \
    Include/glm/gtx/transform.hpp \
    Include/glm/gtx/transform2.hpp \
    Include/glm/gtx/ulp.hpp \
    Include/glm/gtx/unsigned_int.hpp \
    Include/glm/gtx/vec1.hpp \
    Include/glm/gtx/vector_access.hpp \
    Include/glm/gtx/vector_angle.hpp \
    Include/glm/gtx/vector_query.hpp \
    Include/glm/gtx/verbose_operator.hpp \
    Include/glm/gtx/wrap.hpp \
    Include/glm/virtrev/xstream.hpp \
    Include/glm/ext.hpp \
    Include/glm/glm.hpp \
    Include/Octree/array.h \
    Include/Octree/array2d.h \
    Include/Octree/numtraits.h \
    Include/Octree/octree.h \
    Include/Octree/point3d.h \
    Include/Octree/shareddata.h \
    Include/Octree/tinyvector.h \
    Include/OVR/LibOVR/Include/OVR.h \
    Include/OVR/LibOVR/Include/OVRVersion.h \
    Include/OVR/LibOVR/Src/CAPI/GL/CAPI_GL_DistortionRenderer.h \
    Include/OVR/LibOVR/Src/CAPI/GL/CAPI_GL_DistortionShaders.h \
    Include/OVR/LibOVR/Src/CAPI/GL/CAPI_GL_Util.h \
    Include/OVR/LibOVR/Src/CAPI/CAPI_DistortionRenderer.h \
    Include/OVR/LibOVR/Src/CAPI/CAPI_FrameTimeManager.h \
    Include/OVR/LibOVR/Src/CAPI/CAPI_GlobalState.h \
    Include/OVR/LibOVR/Src/CAPI/CAPI_HMDRenderState.h \
    Include/OVR/LibOVR/Src/CAPI/CAPI_HMDState.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_Alg.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_Allocator.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_Array.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_Atomic.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_Color.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_ContainerAllocator.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_Deque.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_File.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_Hash.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_KeyCodes.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_List.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_Lockless.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_Log.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_Math.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_RefCount.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_Std.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_String.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_StringHash.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_SysFile.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_System.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_Threads.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_Timer.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_Types.h \
    Include/OVR/LibOVR/Src/Kernel/OVR_UTF8Util.h \
    Include/OVR/LibOVR/Src/Util/Util_ImageWindow.h \
    Include/OVR/LibOVR/Src/Util/Util_Interface.h \
    Include/OVR/LibOVR/Src/Util/Util_LatencyTest.h \
    Include/OVR/LibOVR/Src/Util/Util_LatencyTest2.h \
    Include/OVR/LibOVR/Src/Util/Util_MagCalibration.h \
    Include/OVR/LibOVR/Src/Util/Util_Render_Stereo.h \
    Include/OVR/LibOVR/Src/OVR_CAPI.h \
    Include/OVR/LibOVR/Src/OVR_CAPI_GL.h \
    Include/OVR/LibOVR/Src/OVR_Device.h \
    Include/OVR/LibOVR/Src/OVR_DeviceConstants.h \
    Include/OVR/LibOVR/Src/OVR_DeviceHandle.h \
    Include/OVR/LibOVR/Src/OVR_DeviceImpl.h \
    Include/OVR/LibOVR/Src/OVR_DeviceMessages.h \
    Include/OVR/LibOVR/Src/OVR_HIDDevice.h \
    Include/OVR/LibOVR/Src/OVR_HIDDeviceBase.h \
    Include/OVR/LibOVR/Src/OVR_HIDDeviceImpl.h \
    Include/OVR/LibOVR/Src/OVR_JSON.h \
    Include/OVR/LibOVR/Src/OVR_LatencyTestImpl.h \
    Include/OVR/LibOVR/Src/OVR_Linux_DeviceManager.h \
    Include/OVR/LibOVR/Src/OVR_Linux_HIDDevice.h \
    Include/OVR/LibOVR/Src/OVR_Linux_HMDDevice.h \
    Include/OVR/LibOVR/Src/OVR_OSX_DeviceManager.h \
    Include/OVR/LibOVR/Src/OVR_OSX_HIDDevice.h \
    Include/OVR/LibOVR/Src/OVR_OSX_HMDDevice.h \
    Include/OVR/LibOVR/Src/OVR_Profile.h \
    Include/OVR/LibOVR/Src/OVR_Recording.h \
    Include/OVR/LibOVR/Src/OVR_Sensor2Impl.h \
    Include/OVR/LibOVR/Src/OVR_Sensor2ImplUtil.h \
    Include/OVR/LibOVR/Src/OVR_SensorCalibration.h \
    Include/OVR/LibOVR/Src/OVR_SensorFilter.h \
    Include/OVR/LibOVR/Src/OVR_SensorFusion.h \
    Include/OVR/LibOVR/Src/OVR_SensorFusionDebug.h \
    Include/OVR/LibOVR/Src/OVR_SensorImpl.h \
    Include/OVR/LibOVR/Src/OVR_SensorImpl_Common.h \
    Include/OVR/LibOVR/Src/OVR_SensorTimeFilter.h \
    Include/OVR/LibOVR/Src/OVR_Stereo.h \
    Include/OVR/LibOVR/Src/OVR_ThreadCommandQueue.h \
    Include/OVR/LibOVR/Src/OVR_Win32_DeviceManager.h \
    Include/OVR/LibOVR/Src/OVR_Win32_DeviceStatus.h \
    Include/OVR/LibOVR/Src/OVR_Win32_HIDDevice.h \
    Include/OVR/LibOVR/Src/OVR_Win32_HMDDevice.h \
    Include/OVR/LibOVR/Src/OVR_Win32_SensorDevice.h \
    Camera.h \
    Crate.h \
    Cube.h \
    GraphicObject.h \
    Input.h \
    Oculus.h \
    Plane.h \
    Scene.h \
    Shader.h \
    Texture.h \
    Utils.h \
    Include/OVR/OVR/LibOVR/Include/OVR.h \
    Include/OVR/OVR/LibOVR/Include/OVRVersion.h \
    Include/OVR/OVR/LibOVR/Src/CAPI/GL/CAPI_GL_DistortionRenderer.h \
    Include/OVR/OVR/LibOVR/Src/CAPI/GL/CAPI_GL_DistortionShaders.h \
    Include/OVR/OVR/LibOVR/Src/CAPI/GL/CAPI_GL_Util.h \
    Include/OVR/OVR/LibOVR/Src/CAPI/CAPI_DistortionRenderer.h \
    Include/OVR/OVR/LibOVR/Src/CAPI/CAPI_FrameTimeManager.h \
    Include/OVR/OVR/LibOVR/Src/CAPI/CAPI_GlobalState.h \
    Include/OVR/OVR/LibOVR/Src/CAPI/CAPI_HMDRenderState.h \
    Include/OVR/OVR/LibOVR/Src/CAPI/CAPI_HMDState.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_Alg.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_Allocator.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_Array.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_Atomic.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_Color.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_ContainerAllocator.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_Deque.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_File.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_Hash.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_KeyCodes.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_List.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_Lockless.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_Log.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_Math.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_RefCount.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_Std.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_String.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_StringHash.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_SysFile.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_System.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_Threads.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_Timer.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_Types.h \
    Include/OVR/OVR/LibOVR/Src/Kernel/OVR_UTF8Util.h \
    Include/OVR/OVR/LibOVR/Src/Util/Util_ImageWindow.h \
    Include/OVR/OVR/LibOVR/Src/Util/Util_Interface.h \
    Include/OVR/OVR/LibOVR/Src/Util/Util_LatencyTest.h \
    Include/OVR/OVR/LibOVR/Src/Util/Util_LatencyTest2.h \
    Include/OVR/OVR/LibOVR/Src/Util/Util_MagCalibration.h \
    Include/OVR/OVR/LibOVR/Src/Util/Util_Render_Stereo.h \
    Include/OVR/OVR/LibOVR/Src/OVR_CAPI.h \
    Include/OVR/OVR/LibOVR/Src/OVR_CAPI_GL.h \
    Include/OVR/OVR/LibOVR/Src/OVR_Device.h \
    Include/OVR/OVR/LibOVR/Src/OVR_DeviceConstants.h \
    Include/OVR/OVR/LibOVR/Src/OVR_DeviceHandle.h \
    Include/OVR/OVR/LibOVR/Src/OVR_DeviceImpl.h \
    Include/OVR/OVR/LibOVR/Src/OVR_DeviceMessages.h \
    Include/OVR/OVR/LibOVR/Src/OVR_HIDDevice.h \
    Include/OVR/OVR/LibOVR/Src/OVR_HIDDeviceBase.h \
    Include/OVR/OVR/LibOVR/Src/OVR_HIDDeviceImpl.h \
    Include/OVR/OVR/LibOVR/Src/OVR_JSON.h \
    Include/OVR/OVR/LibOVR/Src/OVR_LatencyTestImpl.h \
    Include/OVR/OVR/LibOVR/Src/OVR_Linux_DeviceManager.h \
    Include/OVR/OVR/LibOVR/Src/OVR_Linux_HIDDevice.h \
    Include/OVR/OVR/LibOVR/Src/OVR_Linux_HMDDevice.h \
    Include/OVR/OVR/LibOVR/Src/OVR_OSX_DeviceManager.h \
    Include/OVR/OVR/LibOVR/Src/OVR_OSX_HIDDevice.h \
    Include/OVR/OVR/LibOVR/Src/OVR_OSX_HMDDevice.h \
    Include/OVR/OVR/LibOVR/Src/OVR_Profile.h \
    Include/OVR/OVR/LibOVR/Src/OVR_Recording.h \
    Include/OVR/OVR/LibOVR/Src/OVR_Sensor2Impl.h \
    Include/OVR/OVR/LibOVR/Src/OVR_Sensor2ImplUtil.h \
    Include/OVR/OVR/LibOVR/Src/OVR_SensorCalibration.h \
    Include/OVR/OVR/LibOVR/Src/OVR_SensorFilter.h \
    Include/OVR/OVR/LibOVR/Src/OVR_SensorFusion.h \
    Include/OVR/OVR/LibOVR/Src/OVR_SensorFusionDebug.h \
    Include/OVR/OVR/LibOVR/Src/OVR_SensorImpl.h \
    Include/OVR/OVR/LibOVR/Src/OVR_SensorImpl_Common.h \
    Include/OVR/OVR/LibOVR/Src/OVR_SensorTimeFilter.h \
    Include/OVR/OVR/LibOVR/Src/OVR_Stereo.h \
    Include/OVR/OVR/LibOVR/Src/OVR_ThreadCommandQueue.h \
    Include/OVR/OVR/LibOVR/Src/OVR_Win32_DeviceManager.h \
    Include/OVR/OVR/LibOVR/Src/OVR_Win32_DeviceStatus.h \
    Include/OVR/OVR/LibOVR/Src/OVR_Win32_HIDDevice.h \
    Include/OVR/OVR/LibOVR/Src/OVR_Win32_HMDDevice.h \
    Include/OVR/OVR/LibOVR/Src/OVR_Win32_SensorDevice.h \
    Include/OVR/3rdParty/EDID/edid.h \
    Include/OVR/3rdParty/TinyXml/tinyxml2.h \
    spdlog/example/utils.h \
    spdlog/include/spdlog/details/async_log_helper.h \
    spdlog/include/spdlog/details/async_logger_impl.h \
    spdlog/include/spdlog/details/file_helper.h \
    spdlog/include/spdlog/details/format.h \
    spdlog/include/spdlog/details/line_logger.h \
    spdlog/include/spdlog/details/log_msg.h \
    spdlog/include/spdlog/details/logger_impl.h \
    spdlog/include/spdlog/details/mpmc_bounded_q.h \
    spdlog/include/spdlog/details/null_mutex.h \
    spdlog/include/spdlog/details/os.h \
    spdlog/include/spdlog/details/pattern_formatter_impl.h \
    spdlog/include/spdlog/details/registry.h \
    spdlog/include/spdlog/details/spdlog_impl.h \
    spdlog/include/spdlog/sinks/android_sink.h \
    spdlog/include/spdlog/sinks/base_sink.h \
    spdlog/include/spdlog/sinks/dist_sink.h \
    spdlog/include/spdlog/sinks/file_sinks.h \
    spdlog/include/spdlog/sinks/null_sink.h \
    spdlog/include/spdlog/sinks/ostream_sink.h \
    spdlog/include/spdlog/sinks/sink.h \
    spdlog/include/spdlog/sinks/stdout_sinks.h \
    spdlog/include/spdlog/sinks/syslog_sink.h \
    spdlog/include/spdlog/async_logger.h \
    spdlog/include/spdlog/common.h \
    spdlog/include/spdlog/formatter.h \
    spdlog/include/spdlog/logger.h \
    spdlog/include/spdlog/spdlog.h \
    spdlog/include/spdlog/tweakme.h \
    spdlog/tests/catch.hpp \
    spdlog/tests/includes.h \
    spdlog/tests/utils.h

CONFIG += c++11
CONFIG -= qt

#OpenGL
LIBS += -lSDL2 -lGL -lGLU -lSDL2_image -lGLEW
#Oculus
LIBS += -lovr -lpthread -lX11 -ludev -lXinerama -lXrandr
#Boost
LIBS += -lboost_program_options

OTHER_FILES += \
    Include/OVR/LibOVR/Makefile \
    Makefile \
    README.md


QMAKE_CXXFLAGS += -Ofast -Wno-deprecated
QMAKE_LFLAGS += -Ofast -v

DISTFILES += \
    CMakeLists.txt \
    Shaders/basique2D.frag \
    Shaders/couleur2D.frag \
    Shaders/couleur3D.frag \
    Shaders/texture.frag \
    Shaders/basique2D.vert \
    Shaders/couleur2D.vert \
    Shaders/couleur3D.vert \
    Shaders/texture.vert
